### ISSUE TITLE
SLAPI API Plugin: Dynamic Port Assignment

### ISSUE THREAD

**Issue by TheFynx** [ImperialLabs/slapi#60]
- AS A: User/Developer

  - I NEED: SLAPI to assign ports to managed API plugins for internal communication (leave external ports for webhooks or alert services configurable)
  - SO THAT: Users don't have to be concerned about port management or conflicts.

**Comment by TheFynx** [comment]
Assigning bug label because this was suppose to be completed with MVP.

**Comment by aaronblythe** [comment]
Short term, I just updated to read from the config slightly different. https://github.com/ImperialLabs/slapi/commit/32b71ac05970d0ba74f3c6e7e03fc119936b611d
